import type {
  IncomeItem,
  ExpenseItem,
  Loan,
  GoldLoan,
  SavingsItem,
  InvestmentItem,
  FinancialGoal,
  Budget,
} from '../types';

export const INITIAL_DEMO_DATA = {
  profile: {
    full_name: 'Ajay Prasath',
    currency: 'INR',
    monthly_income: 91000,
    theme: 'system' as const,
  },
  incomes: [
    {
      id: 'inc-1',
      source: 'Salary' as const,
      amount: 91000,
      date: new Date().toISOString().split('T')[0],
      description: 'Monthly Corporate Tech Salary',
      is_recurring: true,
      recurrence_frequency: 'monthly' as const,
      notes: 'Primary monthly income deposited on 1st of month',
    },
  ] as IncomeItem[],

  expenses: [
    { id: 'exp-1', category_name: 'Food', amount: 8000, date: new Date().toISOString().split('T')[0], payment_method: 'UPI' as const, merchant: 'Supermarket & Dining', is_recurring: false },
    { id: 'exp-2', category_name: 'Groceries', amount: 6500, date: new Date().toISOString().split('T')[0], payment_method: 'Credit Card' as const, merchant: 'Grocery Store', is_recurring: true },
    { id: 'exp-3', category_name: 'Transport', amount: 5000, date: new Date().toISOString().split('T')[0], payment_method: 'UPI' as const, merchant: 'Fuel & Cab Travel', is_recurring: false },
    { id: 'exp-4', category_name: 'Shopping', amount: 4000, date: new Date().toISOString().split('T')[0], payment_method: 'Credit Card' as const, merchant: 'Clothing & Electronics', is_recurring: false },
    { id: 'exp-5', category_name: 'Utilities', amount: 4500, date: new Date().toISOString().split('T')[0], payment_method: 'Bank Transfer' as const, merchant: 'Electricity & Internet Bills', is_recurring: true },
    { id: 'exp-6', category_name: 'Entertainment', amount: 3500, date: new Date().toISOString().split('T')[0], payment_method: 'UPI' as const, merchant: 'Movies & Outings', is_recurring: false },
    { id: 'exp-7', category_name: 'Medical', amount: 2500, date: new Date().toISOString().split('T')[0], payment_method: 'Cash' as const, merchant: 'Pharmacy', is_recurring: false },
    { id: 'exp-8', category_name: 'Housing', amount: 16000, date: new Date().toISOString().split('T')[0], payment_method: 'Bank Transfer' as const, merchant: 'Apartment Maintenance & Rent', is_recurring: true },
  ] as ExpenseItem[],

  loans: [
    {
      id: 'loan-1',
      name: 'ROAR Personal Loan',
      type: 'Personal Loan' as const,
      original_amount: 100000,
      current_outstanding: 90300,
      emi_amount: 4300,
      interest_rate: 13.5,
      tenure_months: 24,
      remaining_tenure: 21,
      start_date: '2025-11-01',
      due_date_day: 5,
      lender: 'ROAR Finance',
      status: 'active' as const,
      notes: '21 EMIs remaining',
    },
    {
      id: 'loan-2',
      name: 'NAVI Instant Loan',
      type: 'Personal Loan' as const,
      original_amount: 50000,
      current_outstanding: 38400,
      emi_amount: 4800,
      interest_rate: 14.0,
      tenure_months: 12,
      remaining_tenure: 8,
      start_date: '2026-01-01',
      due_date_day: 10,
      lender: 'Navi Finserv',
      status: 'active' as const,
      notes: '8 EMIs remaining',
    },
    {
      id: 'loan-3',
      name: 'RBL Credit EMI',
      type: 'Credit Card' as const,
      original_amount: 15000,
      current_outstanding: 10800,
      emi_amount: 3600,
      interest_rate: 15.0,
      tenure_months: 6,
      remaining_tenure: 3,
      start_date: '2026-05-01',
      due_date_day: 15,
      lender: 'RBL Bank',
      status: 'active' as const,
      notes: '3 EMIs remaining',
    },
    {
      id: 'loan-4',
      name: 'BIKE Loan',
      type: 'Vehicle Loan' as const,
      original_amount: 80000,
      current_outstanding: 54000,
      emi_amount: 4500,
      interest_rate: 11.5,
      tenure_months: 24,
      remaining_tenure: 12,
      start_date: '2025-08-01',
      due_date_day: 7,
      lender: 'HDFC Vehicle Loan',
      status: 'active' as const,
      notes: '12 EMIs remaining',
    },
    {
      id: 'loan-5',
      name: 'TRUE Consumer Loan',
      type: 'Consumer Loan' as const,
      original_amount: 20000,
      current_outstanding: 12000,
      emi_amount: 4000,
      interest_rate: 12.0,
      tenure_months: 6,
      remaining_tenure: 3,
      start_date: '2026-05-01',
      due_date_day: 20,
      lender: 'True Balance',
      status: 'active' as const,
      notes: '3 EMIs remaining',
    },
    {
      id: 'loan-6',
      name: 'Existing Personal Loan (Consolidation Target)',
      type: 'Personal Loan' as const,
      original_amount: 450000,
      current_outstanding: 450000,
      emi_amount: 11200,
      interest_rate: 12.0,
      tenure_months: 60,
      remaining_tenure: 54,
      start_date: '2026-02-01',
      due_date_day: 1,
      lender: 'SBI Personal Loan',
      status: 'active' as const,
      notes: 'Main personal loan eligible for ₹2.5L top-up to consolidate high interest small loans',
    },
  ] as Loan[],

  goldLoans: [
    {
      id: 'gl-1',
      name: 'Gold Loan 1 (Jewellery Pledged)',
      principal_amount: 150000,
      current_outstanding: 150000,
      interest_rate: 10.5,
      interest_type: 'Monthly Simple' as const,
      start_date: '2025-10-15',
      due_date: '2026-10-15',
      monthly_payment: 1312,
      lender: 'Muthoot Finance',
      gold_pledged_description: '45g 22K Gold Bangles & Chains',
      status: 'active' as const,
      notes: 'Monthly interest payment of ~₹1,312',
    },
    {
      id: 'gl-2',
      name: 'Gold Loan 2 (Gold Coins)',
      principal_amount: 120000,
      current_outstanding: 120000,
      interest_rate: 11.0,
      interest_type: 'Monthly Simple' as const,
      start_date: '2026-01-10',
      due_date: '2027-01-10',
      monthly_payment: 1100,
      lender: 'Manappuram Gold',
      gold_pledged_description: '30g Gold Coins',
      status: 'active' as const,
      notes: 'Monthly interest payment of ~₹1,100',
    },
  ] as GoldLoan[],

  savings: [
    { id: 'sav-1', name: 'HDFC Emergency Fund', type: 'Emergency Fund' as const, amount: 75000, expected_return_rate: 5.5, date: new Date().toISOString().split('T')[0], notes: 'Liquid emergency fund' },
    { id: 'sav-2', name: 'Post Office Recurring Deposit', type: 'RD' as const, amount: 45000, expected_return_rate: 6.7, date: new Date().toISOString().split('T')[0], notes: 'Monthly deposit ₹5,000' },
  ] as SavingsItem[],

  investments: [
    { id: 'inv-1', name: 'Nifty 50 Index Mutual Fund', type: 'SIP' as const, invested_amount: 120000, current_value: 142000, monthly_contribution: 5000, expected_return_rate: 12.0, date: new Date().toISOString().split('T')[0] },
    { id: 'inv-2', name: 'Digital Gold Savings', type: 'Gold' as const, invested_amount: 50000, current_value: 58500, monthly_contribution: 2000, expected_return_rate: 9.5, date: new Date().toISOString().split('T')[0] },
    { id: 'inv-3', name: 'Flexi Cap Equity Fund', type: 'Mutual Funds' as const, invested_amount: 80000, current_value: 94000, monthly_contribution: 3000, expected_return_rate: 13.5, date: new Date().toISOString().split('T')[0] },
  ] as InvestmentItem[],

  goals: [
    { id: 'goal-1', name: 'Emergency Fund (6 Months)', target_amount: 180000, current_amount: 75000, target_date: '2027-06-30', monthly_contribution: 10000, priority: 'high' as const, category: 'Emergency' },
    { id: 'goal-2', name: 'Clear High-Interest EMIs', target_amount: 150000, current_amount: 60000, target_date: '2026-12-31', monthly_contribution: 15000, priority: 'high' as const, category: 'Debt Payoff' },
    { id: 'goal-3', name: 'Gold Loan Closure', target_amount: 270000, current_amount: 50000, target_date: '2027-12-31', monthly_contribution: 8000, priority: 'medium' as const, category: 'Gold Loan' },
    { id: 'goal-4', name: 'New Car Down Payment', target_amount: 300000, current_amount: 90000, target_date: '2028-03-31', monthly_contribution: 7000, priority: 'medium' as const, category: 'Purchase' },
  ] as FinancialGoal[],

  budgets: [
    { id: 'b-1', category_name: 'Food', monthly_limit: 8000, month: new Date().getMonth() + 1, year: new Date().getFullYear() },
    { id: 'b-2', category_name: 'Groceries', monthly_limit: 7000, month: new Date().getMonth() + 1, year: new Date().getFullYear() },
    { id: 'b-3', category_name: 'Transport', monthly_limit: 5000, month: new Date().getMonth() + 1, year: new Date().getFullYear() },
    { id: 'b-4', category_name: 'Shopping', monthly_limit: 5000, month: new Date().getMonth() + 1, year: new Date().getFullYear() },
    { id: 'b-5', category_name: 'Entertainment', monthly_limit: 4000, month: new Date().getMonth() + 1, year: new Date().getFullYear() },
  ] as Budget[],
};
